### ISSUE TITLE
Travis CI authentication problem

### ISSUE THREAD

**Issue by eagle-te** [ZennerIoT/element-parsers#22]
Checks result in errors, because of Travis CI authentication problems for https://:@git.zisops.com/code/lib_wmbus.git/

https://travis-ci.org/ZennerIoT/element-parsers/builds/556556807
https://travis-ci.org/ZennerIoT/element-parsers/builds/554315408

```bash
....
$ cd parser_sdk && mix deps.get && mix compile
* Getting lib_wmbus (git@git.zisops.com:code/lib_wmbus.git)
remote: HTTP Basic: Access denied
fatal: Authentication failed for 'https://:@git.zisops.com/code/lib_wmbus.git/'
** (Mix) Command "git --git-dir=.git fetch --force --quiet --progress" failed
The command "cd parser_sdk && mix deps.get && mix compile" failed and exited with 1 during.
Your build has been stopped.
```

**Comment by h4cc** [comment]
Pull requests do not have the needed ENV with credentials to access internal repos for dependencies. No need to change this.
