### ISSUE TITLE
Libelium Smart Parking

### ISSUE THREAD

**Issue by PlumbumDN** [ZennerIoT/element-parsers#3]
Hallo zusammen,

aktuell versuche ich Libelium Parksensoren Smart Parking EU vom IoT-Shop ins Element einzubinden. Der uns zur Verfügung gestellte Parser ist sehr rudimentär und bildet nicht die speziellen Funktionalitäten des Device ab. Bislang werden nur die ersten 2 Byte verarbeitet. Die Frame-spezifischen Feldbelegungen müssen nach meinem Verständnis jeweils als Schleife abgebildet werden. Wie kann dies in elexir möglichst flexibel gelöst werden, ohne jeden Frame explizit ausformulieren zu müssen?

[Smart Parking Technical Guide
[smart_parking_technical_guide.pdf](https://github.com/ZennerIoT/element-parsers/files/1880029/smart_parking_technical_guide.pdf)
](http://www.libelium.com/development/smart-parking/documentation/plug-sense-smart-parking-technical-guide/)

Beste Grüße
/Plumbum

```elixir
defmodule Parser do
  use Platform.Parsing.Behaviour

  # Parser for meter reading of Libelium Smart Parking Sensor
  def parse(<<parking_slot_status::1, battery_status::1, reserved::2, frame_type::4, counter::8, rest::binary>>, _meta) do
    # return value map
    %{
        frame_type: frame_type,
        parking_slot: if(parking_slot_status == 0, do: 99, else: 0),
        battery_state: if(battery_status == 0, do: 1, else: 0), # invert the battery state sesor send 0 for good an 1 for low
                                                                # we switch it to 1 for good an 0 for low
    }
  end
end
```

**Comment by h4cc** [comment]
Hi, das werde ich mir mal anschauen. Der Parser kann ja weitaus mehr nützliche Daten liefern.

In der Dokumentation sind mehrere Firmware (v1, v2, v3) beschrieben die sich anscheinend unterscheiden.

Wisst Ihr welche Firmware auf den Sensoren ist?
Gibt es schon Nachrichten (als HEX) von den Sensoren?

**Comment by PlumbumDN** [comment]
Hi,
Wir haben die V3 auf den Parksensoren. Genauer die 3.01.

Ein aktueller Beispiel payload ist 080A00001F00C60561ED91

**Comment by h4cc** [comment]
Soo, erster Wurf ist da: https://github.com/ZennerIoT/element-parsers/blob/master/lib/libelium_smart_parking_v3.exs

Der Payload `080A00001F00C60561ED91` ist ein "8 -  RSSI Frame". Es gibt da noch ein paar mehr:

* 0 – Info frame
* 1 – Keep-Alive frame
* 2 – Daily update frame
* 3 – Reserved
* 4 – Start frame 1
* 5 – Start frame 2
* 6 – Service frame
* 7 – Downlink frame
* 8 – RSSI frame (Implementiert)

Man kann das praktischerweise direkt im HEX erkennen, also die `8` in `080A...`.

Die Dokumentation ist ziemlich gut, so dass man die weiteren frame_types auch implementieren kann. Sicherer wäre es aber dazu auch echte Payloads zu haben, damit sich da möglichst keine Fehler einschleichen.

Wenn es also noch andere Payloads gibt, diese bitte hier posten damit wir die validieren können.

**Comment by h4cc** [comment]
Mir wurden inzwischen auch Payloads von 0 bis 5 zugespielt, der Parser kann diese jetzt auch Parsen.
Der Frame-Type 6, 7 und 8 scheinen identisch zu sein, werden aber durch einenen anderen Grund ausgelöst.

**Comment by h4cc** [comment]
Eigentlich ist es fast nur "Binary Pattern Matching" mit Elixir. 
Da kann ich diesen Artikel empfehlen: http://www.zohaib.me/binary-pattern-matching-in-elixir/
